name: image_compression
description: A Dart Extension for image package to compress and resize the images.
version: 1.0.5
homepage: https://github.com/eyro-labs/image_compression

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  image: ^4.3.0
  mime: ^2.0.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5
